config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container mt-4" >
  <h1>Restaurants List</h1>
  <ul class="list-group">
    <% @restaurants.each do |restaurant| %>
    <li class="list-group-item"><%= link_to restaurant.name, restaurant_path(restaurant)%></li>
    <% end %>
</ul>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for (@restaurant) do |f|%>
  <%=f.input :name %>
  <%=f.input :address %>
  <%=f.input :category %>
  <%= f.submit%>
<% end %>

app/views/restaurants/show.html.erb
<div class="container mt-4">
<h2><%= @restaurant.name %></h2>
<h3>Address: <%= @restaurant.address %></h3>
<h3>Category: <%= @restaurant.category %></h3>
<ul class="list-group">
<% @restaurant.reviews.each do |review| %>
  <li class="list-group-item"><%= review.content%> Rating: <%= review.rating %></li>

<% end %>
</ul>
<%= link_to "Go to restaurants", restaurants_path, class: "btn btn-primary mt-5"%>
<%= link_to "Leave a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary mt-5" %>
</div>

app/views/reviews/new.html.erb
<div class="container mt-4">
<h1>Review <%= @restaurant.name %></h1>
<%= simple_form_for ([@restaurant, @review]) do |f|%>
  <%=f.input :content %>
  <%=f.input :rating %>
  <%= f.submit "Submit review", class:"btn btn-primary mb-4"%>
<% end %>
<%= link_to "Back to restaurant", restaurant_path(@restaurant), class:"btn btn-primary"%>
</div>